version: '3.3'
services:
  web:
    container_name: web
    build:
      context: ./docker/
      dockerfile: web.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DEV=1
    depends_on:
      - mysql
      - redis
  mysql:
    container_name: mysql
    build:
      context: ./docker/
      dockerfile: mysql.Dockerfile
    volumes:
      - "./scripts/mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'tiktok'
      MYSQL_ROOT_PASSWORD: 'hellomysql_6657edc'
  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"