version: '3.3'
services:
  web:
    container_name: tiktok_web
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - tiktok_mysql
      - tiktok_redis
  mysql:
    container_name: tiktok_mysql
    build:
      context: ./docker/
      dockerfile: mysql.Dockerfile
#    volumes:
#      - "./scripts/mysql:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'tiktok'
      MYSQL_ROOT_PASSWORD: 'hellomysql_6657edc'
  redis:
    container_name: tiktok_redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"